name: Build Both Sides

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04  # Forces an older environment where Python 3.12 won't break things
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize ZMK Workspace
        uses: zmkfirmware/zmk-actions-toolkit-init@main

      - name: Cache West Modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-

      - name: Build Left Side
        uses: zmkfirmware/zmk-actions-toolkit-build@main
        with:
          board: nice_nano_v2
          shield: sofle_left

      - name: Build Right Side
        uses: zmkfirmware/zmk-actions-toolkit-build@main
        with:
          board: nice_nano_v2
          shield: sofle_right

      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sofle_firmware
          path: |
            *.uf2
